spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/order_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:devuser}
spring.datasource.password=${DB_PASSWORD:devpassword}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8081

cors.allowed.origins=${CORS_ALLOWED_ORIGIN:*}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_mX7bAWAwu/.well-known/jwks.json}
spring.application.name=order-service

spring.threads.virtual.enabled=true


application.config.inventory-url=${INVENTORY_URL:http://localhost:8082}


#MONITORING
management.endpoints.web.exposure.include=health,info,prometheus
# (IMPORTANTE) Aggiunge il nome dell'app come 'tag' a tutte le metriche.
# Così su Grafana puoi filtrare le metriche per singola app.
management.metrics.tags.application=${spring.application.name}
# 3. TRACING (TEMPO / OPEN TELEMETRY)
# Campionamento al 100% (cattura tutte le richieste, ottimo in locale)
management.tracing.sampling.probability=1.0
# Dove inviare le tracce (Endpoint HTTP di Tempo)
management.otlp.tracing.endpoint=${TEMPO_APP_URL:http://tempo:4318/v1/traces}

# ==========================================
# 4. DATABASE (PER VEDERE LE QUERY SQL)
# ==========================================
# Attiva il proxy per intercettare le query (richiede la libreria datasource-micrometer)
jdbc.datasource-proxy.enabled=true

# ==========================================
# 5. LOGGING (LOKI)
# ==========================================
# Inietta Trace ID e Span ID direttamente nei log
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
# Variabile custom che passeremo al file logback-spring.xml per l'invio a Loki
app.loki.url=http://loki:3100/loki/api/v1/push
loki.enabled=true
# Passa il nome dell'app a Loki riutilizzando la variabile di Spring
loki.app.name=${LOKI_APP_NAME:${spring.application.name}}
# URL di Loki (versione per il Docker Compose locale)
loki.api.url=${LOKI_APP_URL:http://loki:3100/loki/api/v1/push}
# Credenziali Loki (lasciate vuote in locale)
loki.api.username=
loki.api.password=

# Abilita/Disabilita l'output in console
console.logging.enabled=true

# (Opzionale ma raccomandato) Aggiunge TraceId e SpanId ai log della console
# in modo da vederli anche se guardi i log sul terminale.
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n

